from typing import Any

class Mat4Error(Exception): ...
class Mat4NotSquare(Exception): ...

class Mat4:
    m: Any
    def __init__(self) -> None: ...
    def get_matrix(self): ...
    @classmethod
    def identity(cls): ...
    @classmethod
    def zero(cls): ...
    @classmethod
    def from_list(cls, l): ...
    def transpose(self) -> None: ...
    def get_transpose(self): ...
    def scale(self, x: float, y: float, z: float): ...
    def rotateX(self, angle) -> None: ...
    def rotateY(self, angle) -> None: ...
    def rotateZ(self, angle) -> None: ...
    def __getitem__(self, idx): ...
    def __setitem__(self, idx, item) -> None: ...
    def __mul__(self, rhs): ...
    def __matmul__(self, rhs): ...
    def __imul__(self, rhs): ...
    def __imatmul__(self, rhs): ...
    def __rmul__(self, rhs): ...
