name: Python Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: CI with uv
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"

    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run tests
        run: uv run pytest --ignore=tests/test_Canvas.py tests

      - name: test uv Install
        run: |
          uv init --no-workspace --bare ./TestProject
          uv add nccapy ./TestProject
          cat "import nccapy" >> ./TestProject/test.py
          uv run ./TestProject/test.py
